module.exports = {
  basePath: 'Food_Logistics',
  pathMaps: [
    {
      alias: 'default',
      map: {
        lb1: 'default/lb1',
        'lb-sticky-bottom': 'default/lb1',
        rail1: 'default/rail1',
        rail2: 'default/rail1',
        'infinite-rail': 'default/rail1',
        'infinite-interstitial': 'default/rail1',
        'in-content': 'default/rail1',
        reskin: 'default/reskin',
      },
    },
    {
      alias: 'warehousing',
      map: {
        lb1: 'warehousing/lb1',
        'lb-sticky-bottom': 'warehousing/lb1',
        rail1: 'warehousing/rail1',
        rail2: 'warehousing/rail1',
        'infinite-rail': 'warehousing/rail1',
        'infinite-interstitial': 'warehousing/rail1',
        'in-content': 'warehousing/rail1',
        reskin: 'warehousing/reskin',
      },
    },
    {
      alias: 'transportation',
      map: {
        lb1: 'transportation/lb1',
        'lb-sticky-bottom': 'transportation/lb1',
        rail1: 'transportation/rail1',
        rail2: 'transportation/rail1',
        'infinite-rail': 'transportation/rail1',
        'infinite-interstitial': 'transportation/rail1',
        'in-content': 'transportation/rail1',
        reskin: 'transportation/reskin',
      },
    },
    {
      alias: 'technology',
      map: {
        lb1: 'technology/lb1',
        'lb-sticky-bottom': 'technology/lb1',
        rail1: 'technology/rail1',
        rail2: 'technology/rail1',
        'infinite-rail': 'technology/rail1',
        'infinite-interstitial': 'technology/rail1',
        'in-content': 'technology/rail1',
        reskin: 'technology/reskin',
      },
    },
    {
      alias: 'safety',
      map: {
        lb1: 'safety/lb1',
        'lb-sticky-bottom': 'safety/lb1',
        rail1: 'safety/rail1',
        rail2: 'safety/rail1',
        'infinite-rail': 'safety/rail1',
        'infinite-interstitial': 'safety/rail1',
        'in-content': 'safety/rail1',
        reskin: 'safety/reskin',
      },
    },
    {
      alias: 'sustainability',
      map: {
        lb1: 'sustainability/lb1',
        'lb-sticky-bottom': 'sustainability/lb1',
        rail1: 'sustainability/rail1',
        rail2: 'sustainability/rail1',
        'infinite-rail': 'sustainability/rail1',
        'infinite-interstitial': 'sustainability/rail1',
        'in-content': 'sustainability/rail1',
        reskin: 'sustainability/reskin',
      },
    },
    {
      alias: 'transportation/cold-chain',
      map: {
        lb1: 'transportation/cold-chain/lb1',
        'lb-sticky-bottom': 'transportation/cold-chain/lb1',
        rail1: 'transportation/cold-chain/rail1',
        rail2: 'transportation/cold-chain/rail1',
        'infinite-rail': 'transportation/cold-chain/rail1',
        'infinite-interstitial': 'transportation/cold-chain/rail1',
        'in-content': 'transportation/cold-chain/rail1',
        reskin: 'transportation/cold-chain/reskin',
      },
    },
    {
      alias: 'transportation/3pl-4pl',
      map: {
        lb1: 'transportation/3pl-4pl/lb1',
        'lb-sticky-bottom': 'transportation/3pl-4pl/lb1',
        rail1: 'transportation/3pl-4pl/rail1',
        rail2: 'transportation/3pl-4pl/rail1',
        'infinite-rail': 'transportation/3pl-4pl/rail1',
        'infinite-interstitial': 'transportation/3pl-4pl/rail1',
        'in-content': 'transportation/3pl-4pl/rail1',
        reskin: 'transportation/3pl-4pl/reskin',
      },
    },
    {
      alias: 'safety/risk-compliance',
      map: {
        lb1: 'safety/risk-compliance/lb1',
        'lb-sticky-bottom': 'safety/risk-compliance/lb1',
        rail1: 'safety/risk-compliance/rail1',
        rail2: 'safety/risk-compliance/rail1',
        'infinite-rail': 'safety/risk-compliance/rail1',
        'infinite-interstitial': 'safety/risk-compliance/rail1',
        'in-content': 'safety/risk-compliance/rail1',
        reskin: 'safety/risk-compliance/reskin',
      },
    },
    {
      alias: 'transportation/ocean-ports-carriers',
      map: {
        lb1: 'transportation/ocean-ports-carriers/lb1',
        'lb-sticky-bottom': 'transportation/ocean-ports-carriers/lb1',
        rail1: 'transportation/ocean-ports-carriers/rail1',
        rail2: 'transportation/ocean-ports-carriers/rail1',
        'infinite-rail': 'transportation/ocean-ports-carriers/rail1',
        'infinite-interstitial': 'transportation/ocean-ports-carriers/rail1',
        'in-content': 'transportation/ocean-ports-carriers/rail1',
        reskin: 'transportation/ocean-ports-carriers/reskin',
      },
    },
  ],
};
