module.exports = {
  basePath: 'DSS',
  pathMaps: [
    {
      alias: 'default',
      map: {
        lb1: 'default/lb1',
        // 'lb-sticky-bottom': 'default/lb1',
        rail1: 'default/rail1',
        rail2: 'default/rail1',
        'infinite-rail': 'default/rail1',
        'infinite-interstitial': 'default/rail1',
        'in-content': 'default/rail1',
        reskin: 'default/reskin',
      },
    },
    {
      alias: 'business',
      map: {
        lb1: 'business/lb1',
        // 'lb-sticky-bottom': 'business/lb1',
        rail1: 'business/rail1',
        rail2: 'business/rail1',
        'infinite-rail': 'business/rail1',
        'infinite-interstitial': 'business/rail1',
        'in-content': 'business/rail1',
        reskin: 'business/reskin',
      },
    },
    {
      alias: 'access-control',
      map: {
        lb1: 'access-control/lb1',
        // 'lb-sticky-bottom': 'access-control/lb1',
        rail1: 'access-control/rail1',
        rail2: 'access-control/rail1',
        'infinite-rail': 'access-control/rail1',
        'infinite-interstitial': 'access-control/rail1',
        'in-content': 'access-control/rail1',
        reskin: 'access-control/reskin',
      },
    },
    {
      alias: 'codes-standards',
      map: {
        lb1: 'codes-standards/lb1',
        // 'lb-sticky-bottom': 'codes-standards/lb1',
        rail1: 'codes-standards/rail1',
        rail2: 'codes-standards/rail1',
        'infinite-rail': 'codes-standards/rail1',
        'infinite-interstitial': 'codes-standards/rail1',
        'in-content': 'codes-standards/rail1',
        reskin: 'codes-standards/reskin',
      },
    },
    {
      alias: 'construction-design',
      map: {
        lb1: 'construction-design/lb1',
        // 'lb-sticky-bottom': 'construction-design/lb1',
        rail1: 'construction-design/rail1',
        rail2: 'construction-design/rail1',
        'infinite-rail': 'construction-design/rail1',
        'infinite-interstitial': 'construction-design/rail1',
        'in-content': 'construction-design/rail1',
        reskin: 'construction-design/reskin',
      },
    },
    {
      alias: 'healthcare',
      map: {
        lb1: 'healthcare/lb1',
        // 'lb-sticky-bottom': 'healthcare/lb1',
        rail1: 'healthcare/rail1',
        rail2: 'healthcare/rail1',
        'infinite-rail': 'healthcare/rail1',
        'infinite-interstitial': 'healthcare/rail1',
        'in-content': 'healthcare/rail1',
        reskin: 'healthcare/reskin',
      },
    },
    {
      alias: 'security-safety',
      map: {
        lb1: 'security-safety/lb1',
        // 'lb-sticky-bottom': 'security-safety/lb1',
        rail1: 'security-safety/rail1',
        rail2: 'security-safety/rail1',
        'infinite-rail': 'security-safety/rail1',
        'infinite-interstitial': 'security-safety/rail1',
        'in-content': 'security-safety/rail1',
        reskin: 'security-safety/reskin',
      },
    },
    {
      alias: 'sustainability',
      map: {
        lb1: 'sustainability/lb1',
        // 'lb-sticky-bottom': 'sustainability/lb1',
        rail1: 'sustainability/rail1',
        rail2: 'sustainability/rail1',
        'infinite-rail': 'sustainability/rail1',
        'infinite-interstitial': 'sustainability/rail1',
        'in-content': 'sustainability/rail1',
        reskin: 'sustainability/reskin',
      },
    },
  ],
};
